
let willysCategories = [
  { title: "Kött, chark & fågel", categoryId: 1 },
  { title: "Fryst", categoryId: 3 },
  { title: "Skafferi", categoryId: 2 },
  { title: "Hem & Städ", categoryId: 2 },
  { title: "Mejeri, ost & ägg", categoryId: 2 },
  { title: "Frukt & Grönt", categoryId: 5 },
  { title: "Bröd & Kakor", categoryId: 6 },
  { title: "Fisk & Skaldjur", categoryId: 7 },
  { title: "Dryck", categoryId: 8 },
  { title: "Vegetariskt", categoryId: 9 },
  { title: "Glass, godis & snacks", categoryId: 10 },
  { title: "Färdigmat", categoryId: 11 },
  { title: "Barn", categoryId: 12 },
  { title: "Blommor", categoryId: 13 },
  { title: "Hälsa & Skönhet", categoryId: 14 },
  { title: "Apotek", categoryId: 15 },
  { title: "Trädgård", categoryId: 16 },
  { title: "Husdjur", categoryId: 17 },
  { title: "Tobak", categoryId: 18 },
  { title: "Tändare & tobakstillbehör", categoryId: 19 },
  { title: "Lotter", categoryId: 20 },
  { title: "Tidningar & böcker", categoryId: 21 },
];

let icaCategories = [
  { title: "Kött, fågel & fisk", categoryId: 1 },
  { title: "Vegetariskt", categoryId: 3 },
  { title: "Mejeri, ost & ägg", categoryId: 2 },
  { title: "Frukt & grönt", categoryId: 2 },
  { title: "Bröd & kakor", categoryId: 2 },
  { title: "Fryst", categoryId: 5 },
  { title: "Skafferi", categoryId: 6 },
  { title: "Färdigmat", categoryId: 7 },
  { title: "Dryck", categoryId: 8 },
  { title: "Glass, godis & snacks", categoryId: 9 },
  { title: "Barn", categoryId: 10 },
  { title: "Städ & disk", categoryId: 11 },
  { title: "Hälsa & skönhet", categoryId: 12 },
  { title: "Receptfria läkemedel", categoryId: 13 },
  { title: "Djur", categoryId: 14 },
  { title: "Kök", categoryId: 15 },
  { title: "Hem & fritid", categoryId: 16 },
  { title: "Kiosk", categoryId: 17 },
]

let mathemCategories = [
  { title: "Frukt & Grönt", categoryId: 1 },
  { title: "Mejeri & Ost", categoryId: 3 },
  { title: "Bröd & Bageri", categoryId: 2 },
  { title: "Kött & Chark", categoryId: 2 },
  { title: "Dryck", categoryId: 2 },
  { title: "Skafferi", categoryId: 5 },
  { title: "Fisk & Skaldjur", categoryId: 6 },
  { title: "Hem & Hushåll", categoryId: 7 },
  { title: "Färdigmat & Mellanmål", categoryId: 8 },
  { title: "Glass Godis & Snacks", categoryId: 9 },
  { title: "Barnmat & Tillbehör", categoryId: 10 },
  { title: "Apotek, Hygien & Hälsa", categoryId: 11 },
  { title: "Kryddor & Smaksättare", categoryId: 12 },
  { title: "Djurmat & Tillbehör", categoryId: 13 },
  { title: "Kiosk & Tidningar", categoryId: 14 },
];

module.exports = willysCategories, icaCategories, mathemCategories;
