let dbCategories = {
  kottCharkFagel: 1,
  fryst: 2,
  skafferi: 3,
  hemOchHushall: 4,
  mejeriOstAgg: 5,
  fruktOchGront: 6,
  brodOchKakor: 7,
  dryck: 8,
  vegetariskt: 9,
  glassGodisSnacks: 10,
  fardigmat: 11,
  barn: 12,
  halsaOchSkonhet: 13,
  kiosk: 14
}

let willysCategories = [
  { title: "Kött, chark & fågel", categoryId: dbCategories.kottCharkFagel },
  { title: "Fryst", categoryId: dbCategories.fryst},
  { title: "Skafferi", categoryId: dbCategories.skafferi},
  { title: "Hem & Städ", categoryId: dbCategories.hemOchHushall},
  { title: "Mejeri, ost & ägg", categoryId: dbCategories.mejeriOstAgg },
  { title: "Frukt & Grönt", categoryId: dbCategories.fruktOchGront },
  { title: "Bröd & Kakor", categoryId: dbCategories.brodOchKakor },
  { title: "Fisk & Skaldjur", categoryId: dbCategories.kottCharkFagel },
  { title: "Dryck", categoryId: dbCategories.dryck},
  { title: "Vegetariskt", categoryId: dbCategories.vegetariskt },
  { title: "Glass, godis & snacks", categoryId: dbCategories.glassGodisSnacks },
  { title: "Färdigmat", categoryId: dbCategories.fardigmat },
  { title: "Barn", categoryId: dbCategories.barn },
  { title: "Blommor", categoryId: dbCategories.hemOchHushall },
  { title: "Hälsa & Skönhet", categoryId: dbCategories.halsaOchSkonhet },
  { title: "Apotek", categoryId: dbCategories.halsaOchSkonhet },
  { title: "Trädgård", categoryId: dbCategories.hemOchHushall },
  { title: "Husdjur", categoryId: dbCategories.hemOchHushall },
  { title: "Tobak", categoryId: dbCategories.kiosk },
  { title: "Tändare & tobakstillbehör", categoryId: dbCategories.kiosk },
  { title: "Lotter", categoryId: dbCategories.kiosk },
  { title: "Tidningar & böcker", categoryId: dbCategories.kiosk },
  
];

let icaCategories = [
  { title: "Kött, fågel & fisk", categoryId: 1 },
  { title: "Vegetariskt", categoryId: 3 },
  { title: "Mejeri, ost & ägg", categoryId: 2 },
  { title: "Frukt & grönt", categoryId: 2 },
  { title: "Bröd & kakor", categoryId: 2 },
  { title: "Fryst", categoryId: 5 },
  { title: "Skafferi", categoryId: 6 },
  { title: "Färdigmat", categoryId: 7 },
  { title: "Dryck", categoryId: 8 },
  { title: "Glass, godis & snacks", categoryId: 9 },
  { title: "Barn", categoryId: 10 },
  { title: "Städ & disk", categoryId: 11 },
  { title: "Hälsa & skönhet", categoryId: 12 },
  { title: "Receptfria läkemedel", categoryId: 13 },
  { title: "Djur", categoryId: 14 },
  { title: "Kök", categoryId: 15 },
  { title: "Hem & fritid", categoryId: 16 },
  { title: "Kiosk", categoryId: 17 },
]

let mathemCategories = [
  { title: "Frukt & Grönt", categoryId: 1 },
  { title: "Mejeri & Ost", categoryId: 3 },
  { title: "Bröd & Bageri", categoryId: 2 },
  { title: "Kött & Chark", categoryId: 2 },
  { title: "Dryck", categoryId: 2 },
  { title: "Skafferi", categoryId: 5 },
  { title: "Fisk & Skaldjur", categoryId: 6 },
  { title: "Hem & Hushåll", categoryId: 7 },
  { title: "Färdigmat & Mellanmål", categoryId: 8 },
  { title: "Glass Godis & Snacks", categoryId: 9 },
  { title: "Barnmat & Tillbehör", categoryId: 10 },
  { title: "Apotek, Hygien & Hälsa", categoryId: 11 },
  { title: "Kryddor & Smaksättare", categoryId: 12 },
  { title: "Djurmat & Tillbehör", categoryId: 13 },
  { title: "Kiosk & Tidningar", categoryId: 14 },
];

module.exports = willysCategories, icaCategories, mathemCategories;
